[package]
name = "msquic-async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["tokio"]

[dependencies]
msquic = { git = "https://github.com/masa-koz/msquic.git", branch = "msquic-async" }
bytes = "1.5.0"
futures-io = "0.3.30"
libc = "0.2.153"
once_cell = "1.19.0"
rangemap = "1.5.1"
socket2 = "0.5.6"
test-log = { version = "0.2.15", features = ["trace"] }
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["io-util"], optional = true }
tracing = "0.1.40"

[dev-dependencies]
anyhow = "1.0.80"
futures = "0.3.30"
rcgen = "0.12.1"
tempfile = "3.10.1"
tokio = { version = "1.36.0", features = ["rt", "rt-multi-thread", "time", "macros", "sync"] }
