[package]
name = "msquic-async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
msquic = { path = "../msquic" }
libc = "0.2.0"
once_cell = "1"
futures = "0.3"
thiserror = "1.0.21"
bytes = "1"