[workspace]
members = [
    "msquic-async",
    "h3-msquic",
]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.80"
bytes = "1.5.0"
futures = "0.3.30"
futures-io = "0.3.30"
h3 = { git = "https://github.com/hyperium/h3.git" }
http = "1"
libc = "0.2.153"
msquic = { git = "https://github.com/masa-koz/msquic.git", branch = "msquic-async-20241206" }
msquic-async = { path = "./msquic-async" }
once_cell = "1.19.0"
rangemap = "1.5.1"
rcgen = "0.12.1"
socket2 = "0.5.8"
tempfile = "3.10.1"
test-log = "0.2.15"
thiserror = "1.0.57"
tokio = "1.36.0"
tokio-util = "0.7.9"
tracing = "0.1.40"
