[package]
name = "h3-msquic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
futures = { version = "0.3.28" }
h3 = { git = "https://github.com/hyperium/h3.git" }
msquic-async = { path = "../msquic-async" }
tokio = { version = "1", features = ["io-util"], default-features = false }
tokio-util = { version = "0.7.9" }
