name: CI

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*

permissions: read-all

jobs:
  ci-pass:
    name: CI is green
    runs-on: ubuntu-latest
    needs:
      - style
    steps:
      - run: exit 0

env:
  RUST_BACKTRACE: 1
  toolchain_style: stable
  toolchain_msrv: 1.83.0
  toolchain_h3_msquic_msrv: 1.83.0
  toolchain_doc: nightly-2024-12-11
  toolchain_lint: stable
  toolchain_fuzz: nightly-2024-12-11

  style:
    name: Check Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust ${{ env.toolchain_style }}
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ env.toolchain_style }}
          override: true
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
      - name: cargo fmt --all -- --check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
